package com.android.swingmusic.uicomponent.presentation.theme

import androidx.compose.ui.graphics.Color

// Swing Music Web UI Color Palette

// Light Theme (minimal usage, app primarily uses dark theme)
val light_primary = Color(0xFF006eff)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF234ece)
val light_onPrimaryContainer = Color(0xFFFFFFFF)
val light_secondary = Color(0xFF8e8e93)
val light_onSecondary = Color(0xFF000000)
val light_secondaryContainer = Color(0xFF2c2c2e)
val light_onSecondaryContainer = Color(0xFFffffffde)
val light_tertiary = Color(0xFF636366)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFF48484a)
val light_onTertiaryContainer = Color(0xFFffffffde)
val light_error = Color(0xFFf7635c)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFF8b1e18)
val light_onErrorContainer = Color(0xFFFFFFFF)
val light_outline = Color(0xFF3a3a3c)
val light_background = Color(0xFF181a1c)
val light_onBackground = Color(0xFFffffffde)
val light_surface = Color(0xFF1a1919)
val light_onSurface = Color(0xFFffffffde)
val light_surfaceVariant = Color(0xFF2c2c2e)
val light_onSurfaceVariant = Color(0xFF8e8e93)
val light_inverseSurface = Color(0xFFffffffde)
val light_inverseOnSurface = Color(0xFF181a1c)
val light_inversePrimary = Color(0xFF234ece)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF006eff)
val light_outlineVariant = Color(0xFF3a3a3c)
val light_scrim = Color(0xFF000000)

// Dark Theme (primary theme matching web UI)
val dark_primary = Color(0xFF006eff)
val dark_onPrimary = Color(0xFFFFFFFF)
val dark_primaryContainer = Color(0xFF234ece)
val dark_onPrimaryContainer = Color(0xFFFFFFFF)
val dark_secondary = Color(0xFF8e8e93)
val dark_onSecondary = Color(0xFF181a1c)
val dark_secondaryContainer = Color(0xFF2c2c2e)
val dark_onSecondaryContainer = Color(0xFFffffffde)
val dark_tertiary = Color(0xFF636366)
val dark_onTertiary = Color(0xFF181a1c)
val dark_tertiaryContainer = Color(0xFF48484a)
val dark_onTertiaryContainer = Color(0xFFffffffde)
val dark_error = Color(0xFFf7635c)
val dark_onError = Color(0xFFFFFFFF)
val dark_errorContainer = Color(0xFF8b1e18)
val dark_onErrorContainer = Color(0xFFFFFFFF)
val dark_outline = Color(0xFF3a3a3c)
val dark_background = Color(0xFF181a1c)
val dark_onBackground = Color(0xFFffffffde)
val dark_surface = Color(0xFF1a1919)
val dark_onSurface = Color(0xFFffffffde)
val dark_surfaceVariant = Color(0xFF2c2c2e)
val dark_onSurfaceVariant = Color(0xFF8e8e93)
val dark_inverseSurface = Color(0xFFffffffde)
val dark_inverseOnSurface = Color(0xFF181a1c)
val dark_inversePrimary = Color(0xFF234ece)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFF006eff)
val dark_outlineVariant = Color(0xFF3a3a3c)
val dark_scrim = Color(0xFF000000)

// Content Type Colors (matching web UI)
val artist_color = Color(0xFFff375f)
val album_color = Color(0xFFff9f0a)
val track_color = Color(0xFFff375f)
val folder_color = Color(0xFF40c8e0)
val playlist_color = Color(0xFF5ef784)
val mix_color = Color(0xFFebca89)

val seed = Color(0xFF006eff)

// Web UI specific colors
val webOnSurface = dark_onSurface
val webSecondary = dark_secondary
